# Define all target architectures
#
# For each target define:
#
#  * PREFIX_$(target) variable with the firmware name prefix
#


ARCHIS += zigduino_r2
PREFIX_zigduino_r2 += zigduino

ARCHIS += mega!atmega2560
PREFIX_mega!atmega2560 += mega2560


include ../Makefile.in
